# Generated by Django 4.1.7 on 2023-05-01 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('revenue', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tagline', models.CharField(max_length=50)),
                ('age_limit', models.IntegerField()),
                ('category', models.ManyToManyField(to='movies.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.status')),
            ],
        ),
    ]
